/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AutoInsuranceRouteImport } from './routes/auto-insurance'
import { Route as BusinessInsuranceRouteImport } from './routes/business-insurance'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FamilyInsuranceRouteImport } from './routes/family-insurance'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as HealthInsuranceRouteImport } from './routes/health-insurance'
import { Route as LifeInsuranceRouteImport } from './routes/life-insurance'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as TravelInsuranceRouteImport } from './routes/travel-insurance'
import { Route as InsuranceChildrenRouteImport } from './routes/insurance.children'
import { Route as InsuranceHealthRouteImport } from './routes/insurance.health'
import { Route as InsuranceTravelRouteImport } from './routes/insurance.travel'
import { Route as InsuranceUlipRouteImport } from './routes/insurance.ulip'
import { Route as PlansHealthRouteImport } from './routes/plans.health'
import { Route as PlansTravelRouteImport } from './routes/plans.travel'
import { Route as PlansChildrenIndexRouteImport } from './routes/plans.children.index'
import { Route as PlansChildrenPlanRouteImport } from './routes/plans.children.$plan'
import { Route as PlansEndowmentIndexRouteImport } from './routes/plans.endowment.index'
import { Route as PlansEndowmentPlanRouteImport } from './routes/plans.endowment.$plan'
import { Route as PlansMahilaIndexRouteImport } from './routes/plans.mahila.index'
import { Route as PlansMahilaPlanRouteImport } from './routes/plans.mahila.$plan'
import { Route as PlansMicroIndexRouteImport } from './routes/plans.micro.index'
import { Route as PlansMicroPlanRouteImport } from './routes/plans.micro.$plan'
import { Route as PlansMoneybackIndexRouteImport } from './routes/plans.moneyback.index'
import { Route as PlansMoneybackPlanRouteImport } from './routes/plans.moneyback.$plan'
import { Route as PlansPensionIndexRouteImport } from './routes/plans.pension.index'
import { Route as PlansPensionPlanRouteImport } from './routes/plans.pension.$plan'
import { Route as PlansSinglePremiumIndexRouteImport } from './routes/plans.single-premium.index'
import { Route as PlansSinglePremiumPlanRouteImport } from './routes/plans.single-premium.$plan'
import { Route as PlansTermIndexRouteImport } from './routes/plans.term.index'
import { Route as PlansTermPlanRouteImport } from './routes/plans.term.$plan'
import { Route as PlansUlipIndexRouteImport } from './routes/plans.ulip.index'
import { Route as PlansUlipPlanRouteImport } from './routes/plans.ulip.$plan'
import { Route as PlansWholeLifeIndexRouteImport } from './routes/plans.whole-life.index'
import { Route as PlansWholeLifePlanRouteImport } from './routes/plans.whole-life.$plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoInsuranceRoute = AutoInsuranceRouteImport.update({
  id: '/auto-insurance',
  path: '/auto-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInsuranceRoute = BusinessInsuranceRouteImport.update({
  id: '/business-insurance',
  path: '/business-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyInsuranceRoute = FamilyInsuranceRouteImport.update({
  id: '/family-insurance',
  path: '/family-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInsuranceRoute = HealthInsuranceRouteImport.update({
  id: '/health-insurance',
  path: '/health-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeInsuranceRoute = LifeInsuranceRouteImport.update({
  id: '/life-insurance',
  path: '/life-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelInsuranceRoute = TravelInsuranceRouteImport.update({
  id: '/travel-insurance',
  path: '/travel-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceChildrenRoute = InsuranceChildrenRouteImport.update({
  id: '/insurance/children',
  path: '/insurance/children',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceHealthRoute = InsuranceHealthRouteImport.update({
  id: '/insurance/health',
  path: '/insurance/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceTravelRoute = InsuranceTravelRouteImport.update({
  id: '/insurance/travel',
  path: '/insurance/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceUlipRoute = InsuranceUlipRouteImport.update({
  id: '/insurance/ulip',
  path: '/insurance/ulip',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansHealthRoute = PlansHealthRouteImport.update({
  id: '/plans/health',
  path: '/plans/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansTravelRoute = PlansTravelRouteImport.update({
  id: '/plans/travel',
  path: '/plans/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansChildrenIndexRoute = PlansChildrenIndexRouteImport.update({
  id: '/plans/children/',
  path: '/plans/children/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansChildrenPlanRoute = PlansChildrenPlanRouteImport.update({
  id: '/plans/children/$plan',
  path: '/plans/children/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansEndowmentIndexRoute = PlansEndowmentIndexRouteImport.update({
  id: '/plans/endowment/',
  path: '/plans/endowment/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansEndowmentPlanRoute = PlansEndowmentPlanRouteImport.update({
  id: '/plans/endowment/$plan',
  path: '/plans/endowment/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMahilaIndexRoute = PlansMahilaIndexRouteImport.update({
  id: '/plans/mahila/',
  path: '/plans/mahila/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMahilaPlanRoute = PlansMahilaPlanRouteImport.update({
  id: '/plans/mahila/$plan',
  path: '/plans/mahila/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMicroIndexRoute = PlansMicroIndexRouteImport.update({
  id: '/plans/micro/',
  path: '/plans/micro/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMicroPlanRoute = PlansMicroPlanRouteImport.update({
  id: '/plans/micro/$plan',
  path: '/plans/micro/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMoneybackIndexRoute = PlansMoneybackIndexRouteImport.update({
  id: '/plans/moneyback/',
  path: '/plans/moneyback/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMoneybackPlanRoute = PlansMoneybackPlanRouteImport.update({
  id: '/plans/moneyback/$plan',
  path: '/plans/moneyback/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPensionIndexRoute = PlansPensionIndexRouteImport.update({
  id: '/plans/pension/',
  path: '/plans/pension/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPensionPlanRoute = PlansPensionPlanRouteImport.update({
  id: '/plans/pension/$plan',
  path: '/plans/pension/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSinglePremiumIndexRoute = PlansSinglePremiumIndexRouteImport.update({
  id: '/plans/single-premium/',
  path: '/plans/single-premium/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSinglePremiumPlanRoute = PlansSinglePremiumPlanRouteImport.update({
  id: '/plans/single-premium/$plan',
  path: '/plans/single-premium/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansTermIndexRoute = PlansTermIndexRouteImport.update({
  id: '/plans/term/',
  path: '/plans/term/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansTermPlanRoute = PlansTermPlanRouteImport.update({
  id: '/plans/term/$plan',
  path: '/plans/term/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansUlipIndexRoute = PlansUlipIndexRouteImport.update({
  id: '/plans/ulip/',
  path: '/plans/ulip/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansUlipPlanRoute = PlansUlipPlanRouteImport.update({
  id: '/plans/ulip/$plan',
  path: '/plans/ulip/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansWholeLifeIndexRoute = PlansWholeLifeIndexRouteImport.update({
  id: '/plans/whole-life/',
  path: '/plans/whole-life/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansWholeLifePlanRoute = PlansWholeLifePlanRouteImport.update({
  id: '/plans/whole-life/$plan',
  path: '/plans/whole-life/$plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-insurance': typeof AutoInsuranceRoute
  '/business-insurance': typeof BusinessInsuranceRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/family-insurance': typeof FamilyInsuranceRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/quote': typeof QuoteRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/insurance/children': typeof InsuranceChildrenRoute
  '/insurance/health': typeof InsuranceHealthRoute
  '/insurance/travel': typeof InsuranceTravelRoute
  '/insurance/ulip': typeof InsuranceUlipRoute
  '/plans/health': typeof PlansHealthRoute
  '/plans/travel': typeof PlansTravelRoute
  '/plans/children/$plan': typeof PlansChildrenPlanRoute
  '/plans/endowment/$plan': typeof PlansEndowmentPlanRoute
  '/plans/mahila/$plan': typeof PlansMahilaPlanRoute
  '/plans/micro/$plan': typeof PlansMicroPlanRoute
  '/plans/moneyback/$plan': typeof PlansMoneybackPlanRoute
  '/plans/pension/$plan': typeof PlansPensionPlanRoute
  '/plans/single-premium/$plan': typeof PlansSinglePremiumPlanRoute
  '/plans/term/$plan': typeof PlansTermPlanRoute
  '/plans/ulip/$plan': typeof PlansUlipPlanRoute
  '/plans/whole-life/$plan': typeof PlansWholeLifePlanRoute
  '/plans/children/': typeof PlansChildrenIndexRoute
  '/plans/endowment/': typeof PlansEndowmentIndexRoute
  '/plans/mahila/': typeof PlansMahilaIndexRoute
  '/plans/micro/': typeof PlansMicroIndexRoute
  '/plans/moneyback/': typeof PlansMoneybackIndexRoute
  '/plans/pension/': typeof PlansPensionIndexRoute
  '/plans/single-premium/': typeof PlansSinglePremiumIndexRoute
  '/plans/term/': typeof PlansTermIndexRoute
  '/plans/ulip/': typeof PlansUlipIndexRoute
  '/plans/whole-life/': typeof PlansWholeLifeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-insurance': typeof AutoInsuranceRoute
  '/business-insurance': typeof BusinessInsuranceRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/family-insurance': typeof FamilyInsuranceRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/quote': typeof QuoteRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/insurance/children': typeof InsuranceChildrenRoute
  '/insurance/health': typeof InsuranceHealthRoute
  '/insurance/travel': typeof InsuranceTravelRoute
  '/insurance/ulip': typeof InsuranceUlipRoute
  '/plans/health': typeof PlansHealthRoute
  '/plans/travel': typeof PlansTravelRoute
  '/plans/children/$plan': typeof PlansChildrenPlanRoute
  '/plans/endowment/$plan': typeof PlansEndowmentPlanRoute
  '/plans/mahila/$plan': typeof PlansMahilaPlanRoute
  '/plans/micro/$plan': typeof PlansMicroPlanRoute
  '/plans/moneyback/$plan': typeof PlansMoneybackPlanRoute
  '/plans/pension/$plan': typeof PlansPensionPlanRoute
  '/plans/single-premium/$plan': typeof PlansSinglePremiumPlanRoute
  '/plans/term/$plan': typeof PlansTermPlanRoute
  '/plans/ulip/$plan': typeof PlansUlipPlanRoute
  '/plans/whole-life/$plan': typeof PlansWholeLifePlanRoute
  '/plans/children': typeof PlansChildrenIndexRoute
  '/plans/endowment': typeof PlansEndowmentIndexRoute
  '/plans/mahila': typeof PlansMahilaIndexRoute
  '/plans/micro': typeof PlansMicroIndexRoute
  '/plans/moneyback': typeof PlansMoneybackIndexRoute
  '/plans/pension': typeof PlansPensionIndexRoute
  '/plans/single-premium': typeof PlansSinglePremiumIndexRoute
  '/plans/term': typeof PlansTermIndexRoute
  '/plans/ulip': typeof PlansUlipIndexRoute
  '/plans/whole-life': typeof PlansWholeLifeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-insurance': typeof AutoInsuranceRoute
  '/business-insurance': typeof BusinessInsuranceRoute
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/family-insurance': typeof FamilyInsuranceRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/health-insurance': typeof HealthInsuranceRoute
  '/life-insurance': typeof LifeInsuranceRoute
  '/quote': typeof QuoteRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/insurance/children': typeof InsuranceChildrenRoute
  '/insurance/health': typeof InsuranceHealthRoute
  '/insurance/travel': typeof InsuranceTravelRoute
  '/insurance/ulip': typeof InsuranceUlipRoute
  '/plans/health': typeof PlansHealthRoute
  '/plans/travel': typeof PlansTravelRoute
  '/plans/children/$plan': typeof PlansChildrenPlanRoute
  '/plans/endowment/$plan': typeof PlansEndowmentPlanRoute
  '/plans/mahila/$plan': typeof PlansMahilaPlanRoute
  '/plans/micro/$plan': typeof PlansMicroPlanRoute
  '/plans/moneyback/$plan': typeof PlansMoneybackPlanRoute
  '/plans/pension/$plan': typeof PlansPensionPlanRoute
  '/plans/single-premium/$plan': typeof PlansSinglePremiumPlanRoute
  '/plans/term/$plan': typeof PlansTermPlanRoute
  '/plans/ulip/$plan': typeof PlansUlipPlanRoute
  '/plans/whole-life/$plan': typeof PlansWholeLifePlanRoute
  '/plans/children/': typeof PlansChildrenIndexRoute
  '/plans/endowment/': typeof PlansEndowmentIndexRoute
  '/plans/mahila/': typeof PlansMahilaIndexRoute
  '/plans/micro/': typeof PlansMicroIndexRoute
  '/plans/moneyback/': typeof PlansMoneybackIndexRoute
  '/plans/pension/': typeof PlansPensionIndexRoute
  '/plans/single-premium/': typeof PlansSinglePremiumIndexRoute
  '/plans/term/': typeof PlansTermIndexRoute
  '/plans/ulip/': typeof PlansUlipIndexRoute
  '/plans/whole-life/': typeof PlansWholeLifeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auto-insurance'
    | '/business-insurance'
    | '/claims'
    | '/contact'
    | '/family-insurance'
    | '/get-a-quote'
    | '/health-insurance'
    | '/life-insurance'
    | '/quote'
    | '/travel-insurance'
    | '/insurance/children'
    | '/insurance/health'
    | '/insurance/travel'
    | '/insurance/ulip'
    | '/plans/health'
    | '/plans/travel'
    | '/plans/children/$plan'
    | '/plans/endowment/$plan'
    | '/plans/mahila/$plan'
    | '/plans/micro/$plan'
    | '/plans/moneyback/$plan'
    | '/plans/pension/$plan'
    | '/plans/single-premium/$plan'
    | '/plans/term/$plan'
    | '/plans/ulip/$plan'
    | '/plans/whole-life/$plan'
    | '/plans/children/'
    | '/plans/endowment/'
    | '/plans/mahila/'
    | '/plans/micro/'
    | '/plans/moneyback/'
    | '/plans/pension/'
    | '/plans/single-premium/'
    | '/plans/term/'
    | '/plans/ulip/'
    | '/plans/whole-life/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auto-insurance'
    | '/business-insurance'
    | '/claims'
    | '/contact'
    | '/family-insurance'
    | '/get-a-quote'
    | '/health-insurance'
    | '/life-insurance'
    | '/quote'
    | '/travel-insurance'
    | '/insurance/children'
    | '/insurance/health'
    | '/insurance/travel'
    | '/insurance/ulip'
    | '/plans/health'
    | '/plans/travel'
    | '/plans/children/$plan'
    | '/plans/endowment/$plan'
    | '/plans/mahila/$plan'
    | '/plans/micro/$plan'
    | '/plans/moneyback/$plan'
    | '/plans/pension/$plan'
    | '/plans/single-premium/$plan'
    | '/plans/term/$plan'
    | '/plans/ulip/$plan'
    | '/plans/whole-life/$plan'
    | '/plans/children'
    | '/plans/endowment'
    | '/plans/mahila'
    | '/plans/micro'
    | '/plans/moneyback'
    | '/plans/pension'
    | '/plans/single-premium'
    | '/plans/term'
    | '/plans/ulip'
    | '/plans/whole-life'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auto-insurance'
    | '/business-insurance'
    | '/claims'
    | '/contact'
    | '/family-insurance'
    | '/get-a-quote'
    | '/health-insurance'
    | '/life-insurance'
    | '/quote'
    | '/travel-insurance'
    | '/insurance/children'
    | '/insurance/health'
    | '/insurance/travel'
    | '/insurance/ulip'
    | '/plans/health'
    | '/plans/travel'
    | '/plans/children/$plan'
    | '/plans/endowment/$plan'
    | '/plans/mahila/$plan'
    | '/plans/micro/$plan'
    | '/plans/moneyback/$plan'
    | '/plans/pension/$plan'
    | '/plans/single-premium/$plan'
    | '/plans/term/$plan'
    | '/plans/ulip/$plan'
    | '/plans/whole-life/$plan'
    | '/plans/children/'
    | '/plans/endowment/'
    | '/plans/mahila/'
    | '/plans/micro/'
    | '/plans/moneyback/'
    | '/plans/pension/'
    | '/plans/single-premium/'
    | '/plans/term/'
    | '/plans/ulip/'
    | '/plans/whole-life/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutoInsuranceRoute: typeof AutoInsuranceRoute
  BusinessInsuranceRoute: typeof BusinessInsuranceRoute
  ClaimsRoute: typeof ClaimsRoute
  ContactRoute: typeof ContactRoute
  FamilyInsuranceRoute: typeof FamilyInsuranceRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  HealthInsuranceRoute: typeof HealthInsuranceRoute
  LifeInsuranceRoute: typeof LifeInsuranceRoute
  QuoteRoute: typeof QuoteRoute
  TravelInsuranceRoute: typeof TravelInsuranceRoute
  InsuranceChildrenRoute: typeof InsuranceChildrenRoute
  InsuranceHealthRoute: typeof InsuranceHealthRoute
  InsuranceTravelRoute: typeof InsuranceTravelRoute
  InsuranceUlipRoute: typeof InsuranceUlipRoute
  PlansHealthRoute: typeof PlansHealthRoute
  PlansTravelRoute: typeof PlansTravelRoute
  PlansChildrenPlanRoute: typeof PlansChildrenPlanRoute
  PlansEndowmentPlanRoute: typeof PlansEndowmentPlanRoute
  PlansMahilaPlanRoute: typeof PlansMahilaPlanRoute
  PlansMicroPlanRoute: typeof PlansMicroPlanRoute
  PlansMoneybackPlanRoute: typeof PlansMoneybackPlanRoute
  PlansPensionPlanRoute: typeof PlansPensionPlanRoute
  PlansSinglePremiumPlanRoute: typeof PlansSinglePremiumPlanRoute
  PlansTermPlanRoute: typeof PlansTermPlanRoute
  PlansUlipPlanRoute: typeof PlansUlipPlanRoute
  PlansWholeLifePlanRoute: typeof PlansWholeLifePlanRoute
  PlansChildrenIndexRoute: typeof PlansChildrenIndexRoute
  PlansEndowmentIndexRoute: typeof PlansEndowmentIndexRoute
  PlansMahilaIndexRoute: typeof PlansMahilaIndexRoute
  PlansMicroIndexRoute: typeof PlansMicroIndexRoute
  PlansMoneybackIndexRoute: typeof PlansMoneybackIndexRoute
  PlansPensionIndexRoute: typeof PlansPensionIndexRoute
  PlansSinglePremiumIndexRoute: typeof PlansSinglePremiumIndexRoute
  PlansTermIndexRoute: typeof PlansTermIndexRoute
  PlansUlipIndexRoute: typeof PlansUlipIndexRoute
  PlansWholeLifeIndexRoute: typeof PlansWholeLifeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-insurance': {
      id: '/auto-insurance'
      path: '/auto-insurance'
      fullPath: '/auto-insurance'
      preLoaderRoute: typeof AutoInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-insurance': {
      id: '/business-insurance'
      path: '/business-insurance'
      fullPath: '/business-insurance'
      preLoaderRoute: typeof BusinessInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-insurance': {
      id: '/family-insurance'
      path: '/family-insurance'
      fullPath: '/family-insurance'
      preLoaderRoute: typeof FamilyInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-insurance': {
      id: '/health-insurance'
      path: '/health-insurance'
      fullPath: '/health-insurance'
      preLoaderRoute: typeof HealthInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-insurance': {
      id: '/life-insurance'
      path: '/life-insurance'
      fullPath: '/life-insurance'
      preLoaderRoute: typeof LifeInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-insurance': {
      id: '/travel-insurance'
      path: '/travel-insurance'
      fullPath: '/travel-insurance'
      preLoaderRoute: typeof TravelInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/children': {
      id: '/insurance/children'
      path: '/insurance/children'
      fullPath: '/insurance/children'
      preLoaderRoute: typeof InsuranceChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/health': {
      id: '/insurance/health'
      path: '/insurance/health'
      fullPath: '/insurance/health'
      preLoaderRoute: typeof InsuranceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/travel': {
      id: '/insurance/travel'
      path: '/insurance/travel'
      fullPath: '/insurance/travel'
      preLoaderRoute: typeof InsuranceTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/ulip': {
      id: '/insurance/ulip'
      path: '/insurance/ulip'
      fullPath: '/insurance/ulip'
      preLoaderRoute: typeof InsuranceUlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/health': {
      id: '/plans/health'
      path: '/plans/health'
      fullPath: '/plans/health'
      preLoaderRoute: typeof PlansHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/travel': {
      id: '/plans/travel'
      path: '/plans/travel'
      fullPath: '/plans/travel'
      preLoaderRoute: typeof PlansTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/children/': {
      id: '/plans/children/'
      path: '/plans/children'
      fullPath: '/plans/children/'
      preLoaderRoute: typeof PlansChildrenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/children/$plan': {
      id: '/plans/children/$plan'
      path: '/plans/children/$plan'
      fullPath: '/plans/children/$plan'
      preLoaderRoute: typeof PlansChildrenPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/endowment/': {
      id: '/plans/endowment/'
      path: '/plans/endowment'
      fullPath: '/plans/endowment/'
      preLoaderRoute: typeof PlansEndowmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/endowment/$plan': {
      id: '/plans/endowment/$plan'
      path: '/plans/endowment/$plan'
      fullPath: '/plans/endowment/$plan'
      preLoaderRoute: typeof PlansEndowmentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/mahila/': {
      id: '/plans/mahila/'
      path: '/plans/mahila'
      fullPath: '/plans/mahila/'
      preLoaderRoute: typeof PlansMahilaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/mahila/$plan': {
      id: '/plans/mahila/$plan'
      path: '/plans/mahila/$plan'
      fullPath: '/plans/mahila/$plan'
      preLoaderRoute: typeof PlansMahilaPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/micro/': {
      id: '/plans/micro/'
      path: '/plans/micro'
      fullPath: '/plans/micro/'
      preLoaderRoute: typeof PlansMicroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/micro/$plan': {
      id: '/plans/micro/$plan'
      path: '/plans/micro/$plan'
      fullPath: '/plans/micro/$plan'
      preLoaderRoute: typeof PlansMicroPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/moneyback/': {
      id: '/plans/moneyback/'
      path: '/plans/moneyback'
      fullPath: '/plans/moneyback/'
      preLoaderRoute: typeof PlansMoneybackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/moneyback/$plan': {
      id: '/plans/moneyback/$plan'
      path: '/plans/moneyback/$plan'
      fullPath: '/plans/moneyback/$plan'
      preLoaderRoute: typeof PlansMoneybackPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/pension/': {
      id: '/plans/pension/'
      path: '/plans/pension'
      fullPath: '/plans/pension/'
      preLoaderRoute: typeof PlansPensionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/pension/$plan': {
      id: '/plans/pension/$plan'
      path: '/plans/pension/$plan'
      fullPath: '/plans/pension/$plan'
      preLoaderRoute: typeof PlansPensionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/single-premium/': {
      id: '/plans/single-premium/'
      path: '/plans/single-premium'
      fullPath: '/plans/single-premium/'
      preLoaderRoute: typeof PlansSinglePremiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/single-premium/$plan': {
      id: '/plans/single-premium/$plan'
      path: '/plans/single-premium/$plan'
      fullPath: '/plans/single-premium/$plan'
      preLoaderRoute: typeof PlansSinglePremiumPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/term/': {
      id: '/plans/term/'
      path: '/plans/term'
      fullPath: '/plans/term/'
      preLoaderRoute: typeof PlansTermIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/term/$plan': {
      id: '/plans/term/$plan'
      path: '/plans/term/$plan'
      fullPath: '/plans/term/$plan'
      preLoaderRoute: typeof PlansTermPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/ulip/': {
      id: '/plans/ulip/'
      path: '/plans/ulip'
      fullPath: '/plans/ulip/'
      preLoaderRoute: typeof PlansUlipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/ulip/$plan': {
      id: '/plans/ulip/$plan'
      path: '/plans/ulip/$plan'
      fullPath: '/plans/ulip/$plan'
      preLoaderRoute: typeof PlansUlipPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/whole-life/': {
      id: '/plans/whole-life/'
      path: '/plans/whole-life'
      fullPath: '/plans/whole-life/'
      preLoaderRoute: typeof PlansWholeLifeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/whole-life/$plan': {
      id: '/plans/whole-life/$plan'
      path: '/plans/whole-life/$plan'
      fullPath: '/plans/whole-life/$plan'
      preLoaderRoute: typeof PlansWholeLifePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutoInsuranceRoute: AutoInsuranceRoute,
  BusinessInsuranceRoute: BusinessInsuranceRoute,
  ClaimsRoute: ClaimsRoute,
  ContactRoute: ContactRoute,
  FamilyInsuranceRoute: FamilyInsuranceRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  HealthInsuranceRoute: HealthInsuranceRoute,
  LifeInsuranceRoute: LifeInsuranceRoute,
  QuoteRoute: QuoteRoute,
  TravelInsuranceRoute: TravelInsuranceRoute,
  InsuranceChildrenRoute: InsuranceChildrenRoute,
  InsuranceHealthRoute: InsuranceHealthRoute,
  InsuranceTravelRoute: InsuranceTravelRoute,
  InsuranceUlipRoute: InsuranceUlipRoute,
  PlansHealthRoute: PlansHealthRoute,
  PlansTravelRoute: PlansTravelRoute,
  PlansChildrenPlanRoute: PlansChildrenPlanRoute,
  PlansEndowmentPlanRoute: PlansEndowmentPlanRoute,
  PlansMahilaPlanRoute: PlansMahilaPlanRoute,
  PlansMicroPlanRoute: PlansMicroPlanRoute,
  PlansMoneybackPlanRoute: PlansMoneybackPlanRoute,
  PlansPensionPlanRoute: PlansPensionPlanRoute,
  PlansSinglePremiumPlanRoute: PlansSinglePremiumPlanRoute,
  PlansTermPlanRoute: PlansTermPlanRoute,
  PlansUlipPlanRoute: PlansUlipPlanRoute,
  PlansWholeLifePlanRoute: PlansWholeLifePlanRoute,
  PlansChildrenIndexRoute: PlansChildrenIndexRoute,
  PlansEndowmentIndexRoute: PlansEndowmentIndexRoute,
  PlansMahilaIndexRoute: PlansMahilaIndexRoute,
  PlansMicroIndexRoute: PlansMicroIndexRoute,
  PlansMoneybackIndexRoute: PlansMoneybackIndexRoute,
  PlansPensionIndexRoute: PlansPensionIndexRoute,
  PlansSinglePremiumIndexRoute: PlansSinglePremiumIndexRoute,
  PlansTermIndexRoute: PlansTermIndexRoute,
  PlansUlipIndexRoute: PlansUlipIndexRoute,
  PlansWholeLifeIndexRoute: PlansWholeLifeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
